[project]
name = "ai-stego-benchmark"
version = "0.1.0"
description = "人工智能信息隐藏基准测试平台"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name = "林裕斌" },
  { name = "曾科" },
  { name = "田承金" },
  { name = "吕善翔" }
]

[project.scripts]
ai_stego_benchmark = "ai_stego_benchmark.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}
